#配置
server:
  port: 8088


# Spring 相关
spring:
  application:
    name: mushi-auth-center
  #数据库配置
  datasource:
    url: mysql://localhost:3306/security-oauth?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: Root@123#
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
  #redis 配置
  cache:
    type: redis
  redis:
    password:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8 # 连接词最大链接数
        max-wait: -1ms # 连接池最大阻塞等待时间（负数代表没有限制）
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数 # 链接超时时间 （ms）,连接时间小会导致连接超时
      shutdown-timeout: 100ms


#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.mushi.modules.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    #db-column-underline: true
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    #logic-delete-value: 1
    #logic-not-delete-value: 0
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'
